// <auto-generated />
using System;
using AdDemo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdDemo.DataAccess.Migrations
{
    [DbContext(typeof(AdvertisementDbContext))]
    [Migration("20220203095740_vendors")]
    partial class vendors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdDemo.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AcceptedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaofCultivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Lastmodifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedBy = "",
                            AreaofCultivation = "50Acres",
                            CreatedBy = "Sam",
                            CreatedOn = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 1,
                            Description = "Maize Cultivation",
                            EstimatedPrice = "Rs. 25,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Anuradhapura",
                            VendorId = 0
                        },
                        new
                        {
                            Id = 2,
                            AcceptedBy = "",
                            AreaofCultivation = "20Acres",
                            CreatedBy = "Peter",
                            CreatedOn = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 2,
                            Description = "Cocoa Cultivation",
                            EstimatedPrice = "Rs. 75,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Colombo",
                            VendorId = 0
                        },
                        new
                        {
                            Id = 3,
                            AcceptedBy = "",
                            AreaofCultivation = "100Acres",
                            CreatedBy = "Michael",
                            CreatedOn = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 1,
                            Description = "Carrot Cultivation",
                            EstimatedPrice = "Rs. 100,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kandy",
                            VendorId = 0
                        },
                        new
                        {
                            Id = 4,
                            AcceptedBy = "",
                            AreaofCultivation = "40Acres",
                            CreatedBy = "Mary",
                            CreatedOn = new DateTime(2022, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 4,
                            Description = "Cabbage Cultivation",
                            EstimatedPrice = "Rs. 10,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Badulla",
                            VendorId = 0
                        });
                });

            modelBuilder.Entity("AdDemo.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CropName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfAdvertisements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropName = "Carrot",
                            CropType = "Vegetables",
                            IsAvailable = true,
                            NoOfAdvertisements = 4
                        },
                        new
                        {
                            Id = 2,
                            CropName = "Beans",
                            CropType = "Vegetables",
                            IsAvailable = true,
                            NoOfAdvertisements = 1
                        },
                        new
                        {
                            Id = 3,
                            CropName = "Pears",
                            CropType = "Fruits",
                            IsAvailable = true,
                            NoOfAdvertisements = 10
                        });
                });

            modelBuilder.Entity("AdDemo.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoofClosedAds")
                        .HasColumnType("int");

                    b.Property<int>("NoofInprogressAds")
                        .HasColumnType("int");

                    b.Property<int>("NoofPendingRequests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropId = 0,
                            FullName = "Thilini Anuradha",
                            Location = "Anuradhapura",
                            NoofClosedAds = 0,
                            NoofInprogressAds = 0,
                            NoofPendingRequests = 1
                        },
                        new
                        {
                            Id = 2,
                            CropId = 0,
                            FullName = "Piyumi Thathsarani",
                            Location = "Mathara",
                            NoofClosedAds = 3,
                            NoofInprogressAds = 1,
                            NoofPendingRequests = 4
                        },
                        new
                        {
                            Id = 3,
                            CropId = 0,
                            FullName = "Thanuja Mahendran",
                            Location = "Jaffna",
                            NoofClosedAds = 3,
                            NoofInprogressAds = 0,
                            NoofPendingRequests = 5
                        },
                        new
                        {
                            Id = 4,
                            CropId = 0,
                            FullName = "Umesha Nirmani",
                            Location = "Awissawella",
                            NoofClosedAds = 0,
                            NoofInprogressAds = 3,
                            NoofPendingRequests = 1
                        },
                        new
                        {
                            Id = 5,
                            CropId = 0,
                            FullName = "Nirmani Herath",
                            Location = "Monaragala",
                            NoofClosedAds = 0,
                            NoofInprogressAds = 5,
                            NoofPendingRequests = 4
                        },
                        new
                        {
                            Id = 6,
                            CropId = 0,
                            FullName = "Thilini Erandi",
                            Location = "Galle",
                            NoofClosedAds = 3,
                            NoofInprogressAds = 4,
                            NoofPendingRequests = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
