// <auto-generated />
using System;
using AdDemo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdDemo.DataAccess.Migrations
{
    [DbContext(typeof(AdvertisementDbContext))]
    [Migration("20220131051722_newdata")]
    partial class newdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdDemo.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AcceptedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaofCultivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Lastmodifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedBy = "",
                            AreaofCultivation = "50Acres",
                            CreatedBy = "Sam",
                            CreatedOn = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 1,
                            Description = "Maize Cultivation",
                            EstimatedPrice = "Rs. 25,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Anuradhapura"
                        },
                        new
                        {
                            Id = 2,
                            AcceptedBy = "",
                            AreaofCultivation = "20Acres",
                            CreatedBy = "Peter",
                            CreatedOn = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 2,
                            Description = "Cocoa Cultivation",
                            EstimatedPrice = "Rs. 75,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Colombo"
                        },
                        new
                        {
                            Id = 3,
                            AcceptedBy = "",
                            AreaofCultivation = "100Acres",
                            CreatedBy = "Michael",
                            CreatedOn = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 1,
                            Description = "Carrot Cultivation",
                            EstimatedPrice = "Rs. 100,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kandy"
                        },
                        new
                        {
                            Id = 4,
                            AcceptedBy = "",
                            AreaofCultivation = "40Acres",
                            CreatedBy = "Mary",
                            CreatedOn = new DateTime(2022, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropId = 4,
                            Description = "Cabbage Cultivation",
                            EstimatedPrice = "Rs. 10,000.00",
                            IsAccepted = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            Lastmodifieddate = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Badulla"
                        });
                });

            modelBuilder.Entity("AdDemo.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CropName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfAdvertisements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropName = "Carrot",
                            CropType = "Vegetables",
                            IsAvailable = true,
                            NoOfAdvertisements = 4
                        },
                        new
                        {
                            Id = 2,
                            CropName = "Beans",
                            CropType = "Vegetables",
                            IsAvailable = true,
                            NoOfAdvertisements = 1
                        },
                        new
                        {
                            Id = 3,
                            CropName = "Pears",
                            CropType = "Fruits",
                            IsAvailable = true,
                            NoOfAdvertisements = 10
                        });
                });

            modelBuilder.Entity("AdDemo.Models.Advertisement", b =>
                {
                    b.HasOne("AdDemo.Models.Crop", "crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("crop");
                });
#pragma warning restore 612, 618
        }
    }
}
